name: Bug report
description: Report a reproducible problem in LM Studio Automation
title: "[Bug]: "
labels:
  - bug
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail to reproduce it.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the problem?
      placeholder: Short description of the issue
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps and commands used
      placeholder: |
        1. Run ...
        2. Click ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happened instead?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, LM Studio version, and relevant tooling versions
      placeholder: |
        - OS:
        - LM Studio:
        - llmster/lms:
        - Python:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste relevant snippets from .logs/lmstudio_autostart.log or .logs/lmstudio_tray.log
      render: shell
